---
abstract: 'Serialize object to Perl code'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::Base::Less: '0'
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.13.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PSON
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  PSON:
    file: lib/PSON.pm
    version: '0.03'
requires:
  Encode: '0'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/tokuhirom/PSON/issues
  homepage: https://github.com/tokuhirom/PSON
  repository: git://github.com/tokuhirom/PSON.git
version: '0.03'
